<?php
declare(strict_types=1);
namespace TurmasBridge\Reconciliation;
final class Reconciliation_Attempt_Repository implements Reconciliation_Attempt_Store {
	private \wpdb $wpdb;
	public function __construct(?\wpdb $database = null) { global $wpdb; $this->wpdb = $database ?? $wpdb; }
	public function find_by_key(string $key): ?array { $row = $this->wpdb->get_row($this->wpdb->prepare("SELECT * FROM {$this->table()} WHERE reconciliation_key = %s", $key), 'ARRAY_A'); return is_array($row) ? $row : null; }
	public function find_latest_for_activation(string $key): ?array { $row = $this->wpdb->get_row($this->wpdb->prepare("SELECT * FROM {$this->table()} WHERE activation_operation_key = %s ORDER BY id DESC LIMIT 1", $key), 'ARRAY_A'); return is_array($row) ? $row : null; }
	public function reserve(string $key, string $activation, string $publication, int $form_id, string $fingerprint): Reconciliation_Attempt_Reservation {
		if (! preg_match('/^[A-Za-z0-9:_-]{1,128}$/', $key)) return new Reconciliation_Attempt_Reservation(Reconciliation_Attempt_Reservation::ERROR, null, 'invalid_reconciliation_key');
		$time = current_time('mysql', true); $inserted = $this->wpdb->insert($this->table(), array('reconciliation_key' => $key, 'activation_operation_key' => $activation, 'publication_key' => $publication, 'gravity_form_id' => $form_id, 'snapshot_fingerprint' => $fingerprint, 'state' => Reconciliation_Attempt_State::PENDING, 'result_code' => null, 'evidence_json' => null, 'processing_started_at' => null, 'completed_at' => null, 'created_at' => $time, 'updated_at' => $time));
		if ($inserted !== false) return new Reconciliation_Attempt_Reservation(Reconciliation_Attempt_Reservation::CREATED, $this->find_by_key($key));
		$existing = $this->find_by_key($key); if (! $existing) return new Reconciliation_Attempt_Reservation(Reconciliation_Attempt_Reservation::ERROR, null, 'reconciliation_ledger_write_failed');
		$matches = (string) ($existing['activation_operation_key'] ?? '') === $activation && (string) ($existing['publication_key'] ?? '') === $publication && (int) ($existing['gravity_form_id'] ?? 0) === $form_id && hash_equals((string) ($existing['snapshot_fingerprint'] ?? ''), $fingerprint);
		return new Reconciliation_Attempt_Reservation($matches ? Reconciliation_Attempt_Reservation::EXISTING_MATCH : Reconciliation_Attempt_Reservation::CONFLICT, $existing, $matches ? null : 'reconciliation_identity_conflict');
	}
	public function claim(int $id): Reconciliation_Attempt_Transition { $time = current_time('mysql', true); $updated = $this->wpdb->query($this->wpdb->prepare("UPDATE {$this->table()} SET state = %s, processing_started_at = %s, updated_at = %s WHERE id = %d AND state = %s", Reconciliation_Attempt_State::IN_PROGRESS, $time, $time, $id, Reconciliation_Attempt_State::PENDING)); if ($updated === false) return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::ERROR, null, 'reconciliation_claim_failed'); if ($updated !== 1) return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::STATE_MISMATCH, $this->find_by_id($id)); return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::UPDATED, $this->find_by_id($id)); }
	public function complete(int $id, string $expected, string $state, string $result, array $evidence): Reconciliation_Attempt_Transition { if (! in_array($state, Reconciliation_Attempt_State::terminal(), true)) return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::ERROR, null, 'invalid_reconciliation_state'); $json = $this->encode($evidence); if ($json === false) return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::ERROR, null, 'reconciliation_evidence_invalid'); $time = current_time('mysql', true); $updated = $this->wpdb->query($this->wpdb->prepare("UPDATE {$this->table()} SET state = %s, result_code = %s, evidence_json = %s, completed_at = %s, updated_at = %s WHERE id = %d AND state = %s", $state, $result, $json, $time, $time, $id, $expected)); if ($updated === false) return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::ERROR, null, 'reconciliation_persistence_failed'); if ($updated !== 1) return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::STATE_MISMATCH, $this->find_by_id($id)); return new Reconciliation_Attempt_Transition(Reconciliation_Attempt_Transition::UPDATED, $this->find_by_id($id)); }
	private function find_by_id(int $id): ?array { $row = $this->wpdb->get_row($this->wpdb->prepare("SELECT * FROM {$this->table()} WHERE id = %d", $id), 'ARRAY_A'); return is_array($row) ? $row : null; }
	private function table(): string { return $this->wpdb->prefix . 'turmas_bridge_reconciliation_attempts'; }
	private function encode(array $evidence): string|false { $allowed = array('observed_at','historical_causality','structural_state','form_id','resource_ids','capacity','consumed','reason_code','original_error'); foreach ($evidence as $key => $value) if (! is_string($key) || ! in_array($key, $allowed, true) || ! $this->bounded_value($value)) return false; $json = wp_json_encode($evidence, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); return is_string($json) && strlen($json) <= 8192 ? $json : false; }
	private function bounded_value(mixed $value): bool { if (is_string($value)) return strlen($value) <= 512; if (is_int($value) || is_bool($value) || $value === null) return true; if (! is_array($value) || count($value) > 32) return false; foreach ($value as $item) if (! is_int($item) && ! is_string($item) && ! is_bool($item)) return false; return true; }
}
